name: pipeline-smtp-check
trigger:
- none 

pool:
  name: GeoRisk_AWS_LZ


steps:
- powershell: |
    $smtpServer = "hybrid.sts.rsagroup.com"
    $smtpPort = "25"  

    $recipient = "chethana.maidam@uk.rsagroup.com"
    $subject = "Test Email from Azure DevOps"
    $sender = "chethana.maidam@uk.rsagroup.com"
    $body = "This is a test email sent from an Azure DevOps pipeline."

    $message = New-Object System.Net.Mail.MailMessage($sender, $recipient, $subject, $body)

    $smtp = New-Object System.Net.Mail.SmtpClient($smtpServer, $smtpPort)
    $smtp.EnableSsl = $true 

    $smtp.Send($message)
    Write-Host "Test email sent successfully."
  displayName: 'Send Test Email via SMTP (PowerShell)'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: |
    import smtplib
    from email.message import EmailMessage

    smtp_server = "hybrid.sts.rsagroup.com"
    smtp_port = 25

    sender = "chethana.maidam@uk.rsagroup.com"
    recipient = "chethana.maidam@uk.rsagroup.com"
    subject = "Test Email from Azure DevOps"
    body = "This is a test email sent from an Azure DevOps pipeline using Python."

    msg = EmailMessage()
    msg['From'] = sender
    msg['To'] = recipient
    msg['Subject'] = subject
    msg.set_content(body)

    with smtplib.SMTP(smtp_server, smtp_port) as smtp:
        smtp.send_message(msg)

    print("Test email sent successfully.")
  displayName: 'Send Test Email via SMTP (Python)'
